on:
  push:
    branches:
    - master
name: cleans, build and test app
jobs:
  build:
    permissions:
      id-token: write
      pages: write
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.2'
        channel: 'stable'

    - name: install dependencies
      run: flutter pub get

    - name: build
      run: flutter build web --base-href "/tusks/"

    - uses: actions/upload-pages-artifact@v1
      name: build artifact
      with:
        path: ./build/web
    - uses: actions/deploy-pages@v1
      name: upload
